- hosts: tag_WorkerType_master
  become: yes
  remote_user: ubuntu
  tasks:
    - name: get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: tag_WorkerType_node
  become: yes
  remote_user: ubuntu
  tasks:
    - name: print
      ansible.builtin.debug:
        var: hostvars['ec2-instance-1-master'].join_command
    - name: TCP port 6443 on master is reachable from worker
      wait_for: "host={{ hostvars['ec2-instance-1-master']['ansible_default_ipv4']['address'] }} port=6443 timeout=1"

    - name: join cluster
      shell: "{{ hostvars['ec2-instance-1-master'].join_command }} >> node_joined.log"
      args:
        chdir: /home/ubuntu
        creates: node_joined.log